services:
  postgres:
    image: postgres:15
    container_name: de_postgres
    environment:
      POSTGRES_USER: de_user
      POSTGRES_PASSWORD: de_pass
      POSTGRES_DB: warehouse
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  minio:
    image: minio/minio
    container_name: de_minio
    command: server /data --console-address ":9001"
    environment:
      MINIO_ROOT_USER: minio
      MINIO_ROOT_PASSWORD: minio12345
    ports:
      - "9000:9000"
      - "9001:9001"
    volumes:
      - minio_data:/data

  spark-master:
    image: apache/spark:4.0.2-scala2.13-java17-python3-ubuntu
    container_name: de_spark_master
    command: ["/opt/spark/bin/spark-class", "org.apache.spark.deploy.master.Master"]
    ports:
      - "8080:8080"
      - "7077:7077"
    volumes:
      - ./spark_jobs:/opt/spark_jobs
      - ./data:/opt/data

  spark-worker:
    image: apache/spark:4.0.2-scala2.13-java17-python3-ubuntu
    container_name: de_spark_worker
    depends_on:
      - spark-master
    command: ["/opt/spark/bin/spark-class", "org.apache.spark.deploy.worker.Worker", "spark://spark-master:7077"]
    volumes:
      - ./spark_jobs:/opt/spark_jobs
      - ./data:/opt/data

  airflow:
    image: apache/airflow:2.9.3
    container_name: de_airflow
    depends_on:
      - postgres
      - minio
      - spark-master
      - spark-worker
    environment:
      AIRFLOW__CORE__EXECUTOR: LocalExecutor
      AIRFLOW__DATABASE__SQL_ALCHEMY_CONN: postgresql+psycopg2://de_user:de_pass@postgres:5432/warehouse
      AIRFLOW__CORE__LOAD_EXAMPLES: "false"
      AIRFLOW__CORE__DAGS_ARE_PAUSED_AT_CREATION: "true"
    volumes:
      - ./dags:/opt/airflow/dags
      - ./scripts:/opt/airflow/scripts
      - ./spark_jobs:/opt/airflow/spark_jobs
      - ./sql:/opt/airflow/sql
      - ./data:/opt/airflow/data
    ports:
      - "8088:8080"
    command: >
      bash -c "
      pip install --no-cache-dir sqlalchemy &&
      airflow scheduler & airflow webserver
      "

volumes:
  postgres_data:
  minio_data:
